// Random names from OSE Retainer Random Names (per class, M/F). Thief uses Fighter; Normal Human uses Cleric, Fighter or Magic-User.
export const NAME_LISTS: Record<string, { m: string[]; f: string[] }> = {
  "Cleric": {
    m: ["Abel", "Adrian", "Albin", "Ambrose", "Ambrosius", "Anselm", "Anthony", "Augustine", "Bartholomew", "Benedict", "Bernard", "Blaise", "Bonifacius", "Clement", "Cornelius", "Crispin", "Cyprian", "Damian", "Desmond", "Dominic", "Dunstan", "Edmund", "Elias", "Elisha", "Emmanuel", "Enoch", "Ephraim", "Erasmus", "Eusebius", "Eustace", "Fabian", "Felix", "Florian", "Francis", "Gabriel", "Gilbert", "Gregory", "Hector", "Hilarius", "Horace", "Ignatius", "Isidore", "Jerome", "Julian", "Lawrence", "Leo", "Leonard", "Leopold", "Linus", "Lucian", "Lucius", "Marcus", "Martin", "Matthew", "Matthias", "Maximilian", "Maximus", "Michael", "Nathan", "Nicholas", "Nicodemus", "Noel", "Octavian", "Octavius", "Odo", "Paul", "Peregrine", "Peter", "Philip", "Polycarp", "Quentin", "Quintus", "Raphael", "Reginald", "Roland", "Rufus", "Sebastian", "Severus", "Silas", "Simon", "Stephen", "Sylvester", "Tertullian", "Theodore", "Thomas", "Tiberius", "Timothy", "Tobias", "Urban", "Valentine", "Valerian", "Valerius", "Victor", "Vincent", "Walter", "Wilbur", "Wilfred", "William", "Zacharias", "Zachary"],
    f: ["Agatha", "Agnes", "Alice", "Anastasia", "Anna", "Anne", "Apollonia", "Barbara", "Beatrice", "Bernadette", "Bridget", "Brigid", "Cecilia", "Chastity", "Clara", "Clarice", "Claudia", "Clementia", "Constance", "Deborah", "Dorothea", "Edith", "Eleanor", "Elizabeth", "Emily", "Emma", "Esther", "Etheldreda", "Eugenia", "Eulalia", "Euphemia", "Eva", "Faith", "Felicity", "Fidelia", "Frances", "Gabrielle", "Genevieve", "Gertrude", "Grace", "Hedwig", "Helena", "Hilda", "Hildegard", "Honoria", "Hope", "Ignatia", "Irene", "Joan", "Julia", "Justina", "Katarina", "Katherine", "Lucia", "Lydia", "Marcella", "Margaret", "Martha", "Mary", "Mechtild", "Mercy", "Miriam", "Monica", "Naomi", "Nonna", "Olivia", "Olympia", "Patricia", "Paula", "Perpetua", "Petronilla", "Phoebe", "Placida", "Priscilla", "Prudence", "Rachel", "Radegund", "Rebecca", "Rhoda", "Rosalia", "Ruth", "Sarah", "Scholastica", "Serena", "Sophia", "Susanna", "Tabitha", "Tertia", "Thecla", "Theresa", "Tryphena", "Ursula", "Verity", "Veronica", "Victoria", "Virginia", "Vivian", "Walburga", "Winifred", "Yvonne"],
  },
  "Dwarf": {
    m: ["Alrik", "Arnulf", "Atli", "Azaghal", "Balin", "Barazhad", "Bard", "Bifur", "Bjarni", "Bjorn", "Bolverk", "Bombur", "Brokk", "Bruni", "Dag", "Dain", "Dori", "Durgrim", "Durin", "Egil", "Einar", "Eitri", "Eomer", "Erik", "Eyvind", "Fafnir", "Faldor", "Fargrim", "Fili", "Fjalar", "Floki", "Frogar", "Frosti", "Gamil", "Gimli", "Gizur", "Gloin", "Gorm", "Gravelgut", "Grettir", "Grim", "Gror", "Gudrik", "Gunnar", "Hakon", "Harald", "Helgi", "Hjalmar", "Hrafn", "Hroth", "Ingvar", "Jarl", "Jorik", "Jotun", "Kazdrun", "Keld", "Ketill", "Kili", "Kjell", "Knarr", "Knut", "Kolbein", "Leif", "Loni", "Magnus", "Marn", "Mordak", "Nain", "Njal", "Nori", "Oin", "Olaf", "Ragnar", "Rolf", "Rurik", "Sigmund", "Sigurd", "Sindri", "Skalf", "Skardi", "Skorri", "Starkad", "Sten", "Sven", "Telchar", "Thorgar", "Thorin", "Thorvald", "Thrandur", "Torsten", "Ulfar", "Ulfred", "Valtor", "Varg", "Vermund", "Vidar", "Viggo", "Wulf", "Wyrm", "Yngve"],
    f: ["Alfhild", "Alvit", "Arnora", "Asgerd", "Astrid", "Aud", "Bera", "Bergdis", "Birgit", "Birna", "Borghild", "Brunhild", "Bryndis", "Brynja", "Dagmar", "Dagny", "Disa", "Edda", "Eira", "Eirny", "Embla", "Eydis", "Eyvor", "Fjola", "Freya", "Frida", "Goldvein", "Gro", "Gudny", "Gudrun", "Gunnbjorg", "Gunnlod", "Gunnvor", "Halla", "Halldis", "Hallfrid", "Hallgerd", "Hallveig", "Helga", "Herdis", "Hervor", "Hilda", "Hildigunn", "Hjordis", "Hrefna", "Idun", "Inga", "Ingeborg", "Ingrid", "Ingunn", "Ironbraid", "Jarngerd", "Jarnsaxa", "Jofrid", "Jora", "Jorunn", "Kari", "Katla", "Kolfinna", "Lagertha", "Liv", "Ljot", "Lofn", "Magnhild", "Margit", "Moira", "Nanna", "Njala", "Oda", "Oddny", "Ragna", "Ragnheid", "Rannveig", "Runa", "Saga", "Sif", "Signy", "Sigrun", "Siv", "Skadi", "Solveig", "Steinunn", "Sunniva", "Svala", "Svanhild", "Thorbjorg", "Thorey", "Thorgunna", "Thorhild", "Thorvor", "Thrudd", "Thurid", "Thyra", "Tove", "Unn", "Valdis", "Vigdis", "Vili", "Ylva", "Yrsa"],
  },
  "Elf": {
    m: ["Aegnor", "Aelar", "Aerandir", "Aerendyl", "Aereth", "Aethon", "Alvaron", "Amdir", "Amras", "Amrod", "Anarion", "Ancalagon", "Angrod", "Aradan", "Arathorn", "Arvel", "Beleg", "Berrian", "Caelen", "Caerwyn", "Caladwen", "Calenhir", "Caranthir", "Carric", "Celeborn", "Celebrimbor", "Celegorm", "Cirdan", "Curufin", "Daeron", "Duilin", "Ecthelion", "Egalmoth", "Elandor", "Elenwe", "Elladan", "Elorien", "Elrohir", "Elrond", "Eol", "Erestor", "Erevan", "Faelon", "Faerion", "Faramir", "Fingon", "Finrod", "Finwe", "Galadhrim", "Galadriel", "Galinndan", "Gildor", "Gilgalad", "Glorfindel", "Gwindor", "Hadarai", "Haldir", "Ilvanor", "Imladris", "Immeral", "Ivellios", "Laucian", "Legolas", "Lindir", "Lothiriel", "Mablung", "Maedhros", "Maeglin", "Maethor", "Maglor", "Mindartis", "Mithrandir", "Mithrellas", "Nimrodel", "Orodreth", "Oropher", "Orophin", "Paelias", "Peren", "Quarion", "Rhovanion", "Riardon", "Rolen", "Rumil", "Saelion", "Saeros", "Silvarin", "Soveliss", "Sylvanir", "Tauriel", "Telperion", "Thalion", "Thingol", "Thrandor", "Thranduil", "Turgon", "Vaelor", "Valandil", "Vorondil", "Voronwe"],
    f: ["Adrie", "Aelindis", "Aelindra", "Aelwen", "Aerith", "Ahnaris", "Alenya", "Alleria", "Althaea", "Anaire", "Anastrianna", "Andraste", "Antinua", "Aranel", "Aredhel", "Arianwen", "Arwen", "Belethil", "Bethrynna", "Birel", "Caelith", "Caelynn", "Caladwen", "Celebrian", "Celebriel", "Drusilia", "Eilinel", "Elaith", "Elaria", "Elbereth", "Eldalote", "Eleniel", "Elenwe", "Elwing", "Enna", "Eowyn", "Faelivrin", "Faeriel", "Faylinn", "Felosial", "Finduilas", "Galadriel", "Iaeris", "Idril", "Ielenia", "Ilmare", "Ilnara", "Ilyndra", "Ilyriel", "Indis", "Jelenneth", "Keyleth", "Leshanna", "Lia", "Liadrin", "Lirael", "Lorienne", "Luthien", "Maelis", "Melian", "Meriele", "Mialee", "Miriel", "Naivara", "Nellas", "Nerdanel", "Nerwen", "Nessa", "Nienor", "Nimriel", "Niphredil", "Nyssara", "Olwen", "Orialis", "Quelenna", "Quillathe", "Rhiannon", "Sariel", "Shanairra", "Shava", "Silaqui", "Sildae", "Solanthe", "Sylvanas", "Sylvari", "Thalia", "Theirastra", "Tinuviel", "Tyrande", "Vadania", "Vaeril", "Vaire", "Valanthe", "Vanya", "Varda", "Vereesa", "Veyla", "Xanaphia", "Yavanna", "Ysmera"],
  },
  "Fighter": {
    m: ["Adrian", "Aethelstan", "Aldric", "Alfred", "Alton", "Amos", "Andrew", "Ansel", "Arthur", "Baldwin", "Benjamin", "Beorn", "Bernard", "Bertram", "Brand", "Caleb", "Ceawlin", "Cedric", "Charles", "Chidi", "Conrad", "Cuthred", "Cynric", "Daniel", "David", "Dominic", "Duncan", "Edgar", "Edmund", "Edward", "Edwin", "Egbert", "Egon", "Eldred", "Elias", "Ernest", "Fergus", "Francis", "Garrick", "George", "Gilbert", "Godfrey", "Godric", "Gordon", "Graham", "Harold", "Henry", "Hereward", "Hubert", "Hugh", "Ian", "Isaac", "Jabari", "Jacob", "James", "John", "Jonathan", "Joseph", "Kenneth", "Kwame", "Lawrence", "Leonard", "Malcolm", "Martin", "Matthew", "Michael", "Nathaniel", "Nicholas", "Offa", "Oliver", "Oscar", "Oswald", "Oswin", "Patrick", "Percival", "Peter", "Philip", "Ralph", "Raymond", "Richard", "Robert", "Roger", "Samuel", "Simon", "Stephen", "Tatwine", "Tendai", "Theodore", "Thomas", "Timothy", "Tobias", "Tristan", "Victor", "Walter", "Warren", "Wigstan", "Wihtred", "Wilfred", "William", "Wystan"],
    f: ["Abena", "Abigail", "Ada", "Aelfgifu", "Aelfwynn", "Aethelflaed", "Aldith", "Alice", "Amina", "Anne", "Audrey", "Ayana", "Beatrice", "Bertha", "Brenna", "Bridget", "Bugga", "Caroline", "Catherine", "Charlotte", "Clara", "Cwen", "Cyneburg", "Dorothy", "Eadburh", "Eadgyth", "Ealhswith", "Edith", "Efua", "Eleanor", "Elizabeth", "Emma", "Eormenhild", "Esther", "Ethel", "Evelyn", "Faith", "Florence", "Folasade", "Frances", "Gabriella", "Georgina", "Godiva", "Grace", "Hannah", "Helen", "Imani", "Irene", "Jane", "Joan", "Josephine", "Judith", "Julia", "Kamaria", "Layla", "Leah", "Leofwyn", "Lilian", "Lucy", "Lydia", "Makeda", "Margaret", "Martha", "Mary", "Matilda", "Maud", "Miriam", "Nandi", "Naomi", "Ngozi", "Nia", "Nkechi", "Nora", "Olivia", "Osburh", "Patricia", "Rachel", "Rebecca", "Roxana", "Ruth", "Sade", "Samira", "Sarah", "Sophia", "Susan", "Tabitha", "Thandiwe", "Theresa", "Ursula", "Valerie", "Victoria", "Violet", "Virginia", "Winifred", "Wulfrun", "Wynflaed", "Yaa", "Yasmin", "Zola", "Zuri"],
  },
  "Halfling": {
    m: ["Adelard", "Alton", "Anson", "Appleby", "Artie", "Bandobras", "Banks", "Barliman", "Barnaby", "Basil", "Bellamy", "Benwick", "Bertram", "Bilberry", "Bilbo", "Boffin", "Boffo", "Bolger", "Bracegirdle", "Bramble", "Brandybuck", "Brockhouse", "Bunce", "Bungo", "Burrows", "Butterbur", "Chubb", "Cottar", "Cotton", "Diggle", "Dodd", "Drogo", "Fairbairn", "Farthing", "Folco", "Fortinbras", "Fredegar", "Frodo", "Gamgee", "Gamwich", "Gardner", "Goodbody", "Goodenough", "Gorbadoc", "Gorhendad", "Greatbarrow", "Greenhand", "Grubb", "Gundabald", "Hamfast", "Hayseed", "Hayward", "Headstrong", "Hending", "Hildibrand", "Hobb", "Holman", "Hornblower", "Ilberic", "Isengrim", "Isumbras", "Lightfoot", "Longbottom", "Lotho", "Marcho", "Marmaduke", "Meriadoc", "Moss", "Odo", "Peregrin", "Pippin", "Polo", "Ponto", "Proudfoot", "Puddle", "Quickstep", "Rollo", "Rorimac", "Roundhill", "Rufus", "Rumble", "Samwise", "Sandyman", "Saradoc", "Smallburrow", "Tobold", "Togo", "Took", "Tunnelly", "Underhill", "Weatherwax", "Whitfoot", "Whitfurrows", "Whitlock", "Wilcome", "Wilibald", "Willows", "Woolfoot", "Yarberry", "Yellowley"],
    f: ["Amaranth", "Amaryllis", "Angelica", "Anise", "Asphodel", "Begonia", "Belladonna", "Bess", "Betsy", "Blossom", "Bluebell", "Buttercup", "Camellia", "Cherry", "Cinnamon", "Clover", "Cora", "Cowslip", "Daffodil", "Dahlia", "Daisy", "Diamond", "Dilly", "Donnamira", "Dora", "Eglantine", "Elanor", "Esme", "Estella", "Fern", "Flora", "Foxglove", "Fuchsia", "Gardenia", "Ginger", "Goldilocks", "Hazel", "Heather", "Holly", "Honeydew", "Honeysuckle", "Hyacinth", "Iris", "Ivy", "Jasmine", "Juniper", "Larkspur", "Lavender", "Lila", "Lily", "Lobelia", "Mabel", "Maggie", "Magnolia", "Maisie", "Mallow", "Marguerite", "Marigold", "Marjoram", "Merrybell", "Millicent", "Mirabella", "Myrtle", "Narcissa", "Nell", "Nettle", "Nutmeg", "Orchid", "Pansy", "Pearl", "Pennyroyal", "Peony", "Periwinkle", "Petunia", "Pimpernel", "Pippa", "Poppy", "Primrose", "Primula", "Rosamund", "Rose", "Ruby", "Saffron", "Sage", "Snowdrop", "Sorrel", "Sunflower", "Susie", "Thistle", "Tilda", "Treacle", "Tulip", "Tuppence", "Verbena", "Violet", "Wilhelmina", "Willow", "Wisteria", "Yarrow", "Zinnia"],
  },
  "Magic-User": {
    m: ["Abraxas", "Aeetes", "Alaric", "Alastor", "Alatar", "Amon", "Anaxagoras", "Anselm", "Antonidas", "Arcturus", "Arion", "Aurelius", "Azrael", "Balthazar", "Beren", "Cadmus", "Cagliostro", "Caligula", "Cassian", "Corvin", "Cyprian", "Daedalus", "Darius", "Dorian", "Eldric", "Eliphas", "Emeric", "Eryx", "Faeron", "Faustus", "Galen", "Gavriel", "Gideon", "Gregorius", "Hadrian", "Hermes", "Icarus", "Ignatius", "Imhotep", "Isidore", "Jareth", "Joram", "Kael", "Kelthuzad", "Khadgar", "Leander", "Leofric", "Lucan", "Lucius", "Magnus", "Marcellus", "Medivh", "Merlin", "Mervyn", "Mordecai", "Myrddin", "Nectanebo", "Nereus", "Nicanor", "Oberon", "Orpheus", "Osric", "Pallando", "Paracelsus", "Peregrine", "Philemon", "Prospero", "Ptolemy", "Pythagoras", "Quillon", "Quirinus", "Radagast", "Rasmus", "Ravel", "Remiel", "Rhonin", "Roderic", "Salazar", "Saruman", "Severian", "Silas", "Solon", "Taliesin", "Thaddeus", "Thales", "Theon", "Theophilus", "Thoth", "Tycho", "Ulric", "Uriel", "Valdemar", "Valerius", "Veyron", "Vortigern", "Xenon", "Zephyr", "Zoltan", "Zorion", "Zoroaster"],
    f: ["Aegwynn", "Agamede", "Aglaonike", "Alcina", "Alectra", "Althea", "Amara", "Andromeda", "Ariadne", "Armida", "Aurelia", "Aveline", "Bellatrix", "Briseis", "Bryony", "Callista", "Calpurnia", "Calypso", "Cassandra", "Cassia", "Celandine", "Celestia", "Circe", "Cressida", "Damaris", "Delia", "Delphine", "Elara", "Elysia", "Eudora", "Evadne", "Faustina", "Freesia", "Galatea", "Hecate", "Helena", "Hermione", "Hypatia", "Ianthe", "Ilyana", "Isadora", "Ismene", "Isolde", "Jessamine", "Junia", "Kalliope", "Keziah", "Lavinia", "Leontine", "Lysandra", "Marcella", "Medea", "Melisande", "Melusine", "Mirabel", "Morgana", "Morgause", "Nehalennia", "Nerissa", "Nimue", "Nyx", "Octavia", "Oenone", "Ondine", "Ophelia", "Oriana", "Panacea", "Persephone", "Phaedra", "Philomena", "Pythia", "Rhea", "Rhiannon", "Rhoswen", "Rowena", "Sabina", "Sapphira", "Selene", "Seraphina", "Sibyl", "Soraya", "Sycorax", "Tabitha", "Tamsin", "Thalia", "Theia", "Theodora", "Titania", "Urania", "Valentina", "Valeria", "Vespera", "Vesta", "Vivienne", "Xenia", "Ysabel", "Yseult", "Zelpha", "Zenobia", "Zephyra"],
  },
};
